### ISSUE TITLE
no matches for kind "KubeSchedulerConfiguration" in version "kubescheduler.config.k8s.io/v1beta1"

### ISSUE THREAD

**Issue by Chenhait** [lwabish/k8s-scheduler#1]
Hi, i read your wonderful work!
however, when i try to 
kubectl apply -f hack/config-sample.yml
there is a error
![image](https://user-images.githubusercontent.com/68895932/160824289-823b573c-06ec-403a-8c5b-e638c87de312.png)
thank you very much if any advance!!!

**Comment by lwabish** [comment]
maybe you could check your kubernetes cluster version first

**Comment by Chenhait** [comment]
thank you so much for your reply!!!
 my  kubernetes cluster version is v1.17.4
![image](https://user-images.githubusercontent.com/68895932/160844576-2a2582b5-c1bc-4aa1-a95d-1e4fca8f1290.png)

And i find that KubeSchedulerConfiguration is not a public api. It's just a config for scheduler.
So, do you have more detailed toturial for the beginer to run this wonderful work?
Thank you again! you are such a good people!

Thank you again! you are such a good people!

**Comment by Chenhait** [comment]
I tried
make build
and then kubectl apply -f hack/scheduler-test.yml
but the pod scheduler-test-5d5ff8b4d5-tkhmr is Pending.



did I miss some steps?

Thank you again! you are such a good people!
best wishes!!!
