### ISSUE TITLE
参考链接无法正常浏览

### ISSUE THREAD

**Issue by AbstractWorld** [lwabish/k8s-scheduler#2]
你好，我在看ReadMe.md链接中的文章时发现无法正常浏览，只可看到标题和标签，正文和评论都无法正常浏览，请问是后台限制了吗？

**Comment by lwabish** [comment]
感谢反馈，已经修复了

**Comment by lesserror** [comment]
您好，链接好像又失效了，请问能修复一下吗~

**Comment by lwabish** [comment]
已修复。确实得完善下监控告警了
